steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/frontend'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build --build-arg=REACT_APP_URI_USER_SVC_ARG=${_REACT_APP_URI_USER_SVC} --build-arg=REACT_APP_URI_MATCHING_SVC_ARG=${_REACT_APP_URI_MATCHING_SVC} --build-arg=REACT_APP_URI_COMMUNICATION_SVC_ARG=${_REACT_APP_URI_COMMUNICATION_SVC} --build-arg=REACT_APP_URI_QUESTION_SVC_ARG=${_REACT_APP_URI_QUESTION_SVC} .'
      ]
