steps:
  - name: node
    dir: 'apps/user-service'
    entrypoint: npm
    args: ['install']
  - name: node
    dir: 'apps/user-service'
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'ENV=${_ENV}'
      - 'DB_CLOUD_URI=${_DB_CLOUD_URI}'
      - 'FRONTEND_URL=${_FRONTEND_URL}'
  - name: node
    dir: 'apps/user-service'
    entrypoint: npm
    args: ['run', 'build']
