steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/question-service'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build --build-arg=ENV_ARG=${_ENV} --build-arg=DB_CLOUD_URI_ARG=${_DB_CLOUD_URI} .'
      ]
