steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/question-service'
    args:
      [
        'build',
        '-t',
        'asia.gcr.io/cs3219-g45/cs3219-project-ay2223s1-g45/cs3219-g45-question-service:latest',
        '--build-arg'
        'ENV_ARG=${_ENV}',
        '--build-arg',
        'DB_CLOUD_URI_ARG=${_DB_CLOUD_URI}',
        '.'
      ]
images:
  - 'asia.gcr.io/cs3219-g45/cs3219-project-ay2223s1-g45/cs3219-g45-question-service:latest'
