steps:
  - name: node
    dir: 'apps/question-service'
    entrypoint: npm
    args: ['install']
  - name: node
    dir: 'apps/question-service'
    entrypoint: npm
    args: ['run', 'create-env-and-build']
    env:
      - 'ENV=${_ENV}'
      - 'DB_CLOUD_URI=${_DB_CLOUD_URI}'
