steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'apps/question-service'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t asia.gcr.io/cs3219-g45/cs3219-project-ay2223s1-g45/cs3219-g45-question-service:c5ad252efea9c68d4c67c77b6c77de5219ec2a11 --build-arg ENV_ARG=${_ENV} --build-arg DB_CLOUD_URI_ARG=${_DB_CLOUD_URI} .
